/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stockmaintenance;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 * @author          Carmen Dominguez
 * @created         15 September 2016
 * @updated         18 September 2016
 * @Description     This is the main interface of StockMaintenance
 */
public class StockMaster extends javax.swing.JFrame {
    
    //variables
    Connection conn;

    /**
     * Creates new form StockMaster
     */
    
    public StockMaster() {
        super("Stock Master");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCode = new javax.swing.JLabel();
        lblDesc = new javax.swing.JLabel();
        lblMetric = new javax.swing.JLabel();
        lblMetric1 = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        lblQuanto = new javax.swing.JLabel();
        cmbCode = new javax.swing.JComboBox();
        txtDesc = new javax.swing.JTextField();
        txtSize = new javax.swing.JTextField();
        txtMetric = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtQuanto = new javax.swing.JTextField();
        btnDbConn = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCode.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblCode.setText("Stack Code");

        lblDesc.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblDesc.setText("Description");

        lblMetric.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblMetric.setText("Metric");

        lblMetric1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblMetric1.setText("Unit Size");

        lblPrice.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblPrice.setText("Price");

        lblQuanto.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblQuanto.setText("Quantity in Stock");

        cmbCode.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        cmbCode.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtDesc.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        txtSize.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        txtMetric.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        txtPrice.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        txtQuanto.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        btnDbConn.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnDbConn.setText("Connect to DB");

        btnDelete.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnDelete.setText("Delete");

        btnClear.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnClear.setText("Clear");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbCode, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDesc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblQuanto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtQuanto, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMetric1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSize, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMetric)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtMetric, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPrice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDbConn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(202, 202, 202)
                        .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCode)
                    .addComponent(cmbCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDesc)
                    .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMetric)
                    .addComponent(txtMetric, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMetric1)
                    .addComponent(txtSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrice)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuanto)
                    .addComponent(txtQuanto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDbConn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Method to choose which button's action will be performed
   private void chooseBtn (java.awt.event.ActionEvent evt)
   {
       
   }
   
   //Method to connect to the database
   private void connectDB()
   {
       //Load the Driver
        try 
        {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            System.out.println("Driver succesfully downloaded");
            
        } catch (ClassNotFoundException c) 
        {
            System.out.println("Could not successfully download driver");
        }

        //Connect to the database
        try {
            
            String filename = "jdbc:odbc:StockDB";

            conn = DriverManager.getConnection(filename);

            JOptionPane.showMessageDialog(null, "Connection to StockDB is successful.");

        } catch (SQLException e) 
        {
            System.out.println("StockMaster, connectDB: " + e);
            JOptionPane.showMessageDialog(null, "Connection to StockDB was unsuccessful.");
        }
        
        //Populate the comboBox
        
   }
   
   //Method to search through the database
   private void searchDb()
   {
       
   }
   
   //Method to delete a record in the database
   private void deleteRec()
   {
       
   }
   
   //Method to clear all the fields
   private void clear()
   {
       txtDesc.setText("");
       txtMetric.setText("");
       txtPrice.setText("");
       txtQuanto.setText("");
       txtSize.setText("");
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDbConn;
    private javax.swing.JButton btnDelete;
    private javax.swing.JComboBox cmbCode;
    private javax.swing.JLabel lblCode;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblMetric;
    private javax.swing.JLabel lblMetric1;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblQuanto;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextField txtMetric;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuanto;
    private javax.swing.JTextField txtSize;
    // End of variables declaration//GEN-END:variables
}
